import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import Link from "next/link";
import { ReactQueryProvider } from "@/app/providers/react-query";
import { Logout } from "@/domain/auth/components/logout";
import { getUserProfile } from "@/domain/auth/utils/get-user-profile";
import { TOKEN_COOKIE_NAME } from "@/utils/api/token-cookie";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Users",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const token = cookies().get(TOKEN_COOKIE_NAME)?.value;
  console.log("LAYOUT RENDER");
  const user = await getUserProfile(token);

  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full`}>
        <header className="text-lg p-4 border-b-2">
          <div className="flex justify-between">
            {user ? (
              <div>
                User name: <span className="text-indigo-600">{user.name}</span>
              </div>
            ) : (
              <Link href="/login" className="underline text-blue-500">
                Login
              </Link>
            )}
            <Link href="/about" className="underline text-blue-500">
              About
            </Link>
            {user && (
              <div>
                <Link href="/users" className="underline text-blue-500">
                  Users
                </Link>
              </div>
            )}
            {user && <Logout />}
          </div>
        </header>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
